<h3>Represent Data in adjancency matrix </h3>

In [139]:
import numpy as np
import itertools

graph = open("C:/Users/nizar/Desktop/wiss/heur/heur003.gr", 'r')
p,cep,n_vertices, n_edges=graph.readline().split()    #get first line of data in variables
adjacency_matrix = [[0] * int(n_vertices) for _ in range(int(n_vertices))]  #Declare a n_edges dimension matrix full of zeros 
for line in graph:     #Traverse the matrix
    u, v = map(int, line.split())    #Split the line into two variables since we have 2 integers
    adjacency_matrix[u-1][v-1] = 1   #Replacing zeros with 1 if there is a link between 2 vertices
    adjacency_matrix[v-1][u-1] = 1
#print(adjacency_matrix)
a=np.matrix(adjacency_matrix)        #We want a numpy matrix huh ;)
print(a) 


[[0 1 1 ... 0 0 0]
 [1 0 1 ... 0 1 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 1]
 [0 1 0 ... 1 0 1]
 [0 0 0 ... 1 1 0]]


<h3>For visualisation and optimisation purposes, I only considered the triangular bottom half of the adjacency matrix.</h3>

In [140]:
b=np.tril(a)  #For esthetical reasons, I only keep the lower part of the matrix, no data is lost though
#for i in range(len(b)):
    #for j in range(i):
       # print(b[i][j])
print(b)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 1 1 0]]


<h4>Find squares function, but I didn't work with it actually, don't consider this function. Though, it helped me a lot to define the next function</h4>

In [141]:
def find_squares_ones(matrix):
    squares = []                    # initialize an empty list to store the squares of ones
    for i in range(len(matrix)):    # loop through the rows of the matrix
        for j in range(i+1):  # loop through the columns, but only the triangular half bottom of the adjacency matrix.
            if matrix[i][j] == 1:        # if the current element is 1, start looking for a square
                square_size = 1  # start with a square of size 1
                # keep increasing the size of the square as long as all the elements within the square are 1's
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                # if we find a square of size greater than 1, add it to the list of squares
                if square_size > 1:
                    squares.append([[1]*square_size]*square_size)
    return squares  # return the list of squares of ones
find_squares_ones(b)

[[[1, 1], [1, 1]],
 [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
 [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1]],
 [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
 [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1]],
 [[1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1]],
 [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
 [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1]],
 [[1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1]],
 [[1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1],
  [1, 1, 1

Perfect, now i have my squares. <br>
Basically, this function takes a matrix as an argument and seeks for every possible square of 1s.<br>
E.G :<br>
1 1 1<br>
1 1 1<br>
1 1 1<br>
or :<br>
1 1 <br>
1 1<br>
or whatever <br>
The return statement is a list. Each element is also a list that contains the coordinates of the top leftmost element and the bottom rightmost element.

<h3>Find squares function: this function extracts the squares in the matrix that only contain ones in them.</h3>
<h3>The output is a list with containing the coordinates of the top left element and bottom right element of each square</h3>

In [142]:
def find_squares(matrix):
    squares = []
    sizes = []
    for i in range(len(matrix)):   # initialize an empty list to store the squares of ones
        for j in range(i+1):       # loop through the rows of the matrix
            if matrix[i][j] == 1:  # loop through the columns, but only the triangular half bottom of the adjacency matrix.
                square_size = 1    # if the current element is 1, start looking for a square
                # start with a square of size 1
                # keep increasing the size of the square as long as all the elements within the square are 1's
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                    # i + square_size < len(matrix) : ensures that our square bottom row is inside our matrix
                    # j + square_size < len(matrix[i]) : ensures that the right column of the square is inside it too
                    # all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)) : ensures that all element of the square is 1
                # if we find a square of size greater than 1, add it to the list of squares and sizes
                if square_size > 1:
                    squares.append([(i, j), (i + square_size - 1, j + square_size - 1)]) # Get the sizes in a list
                    sizes.append(square_size)
    return squares, sizes
result, sizes = find_squares(b)
result

[[(2, 0), (3, 1)],
 [(3, 0), (5, 2)],
 [(3, 1), (4, 2)],
 [(4, 0), (7, 3)],
 [(4, 1), (6, 3)],
 [(4, 2), (5, 3)],
 [(5, 0), (9, 4)],
 [(5, 1), (8, 4)],
 [(5, 2), (7, 4)],
 [(5, 3), (6, 4)],
 [(6, 0), (11, 5)],
 [(6, 1), (10, 5)],
 [(6, 2), (9, 5)],
 [(6, 3), (8, 5)],
 [(6, 4), (7, 5)],
 [(7, 0), (11, 4)],
 [(7, 1), (11, 5)],
 [(7, 2), (11, 6)],
 [(7, 3), (10, 6)],
 [(7, 4), (9, 6)],
 [(7, 5), (8, 6)],
 [(8, 0), (11, 3)],
 [(8, 1), (11, 4)],
 [(8, 2), (11, 5)],
 [(8, 3), (11, 6)],
 [(8, 4), (11, 7)],
 [(8, 5), (10, 7)],
 [(8, 6), (9, 7)],
 [(9, 0), (12, 3)],
 [(9, 1), (11, 3)],
 [(9, 2), (11, 4)],
 [(9, 3), (11, 5)],
 [(9, 4), (11, 6)],
 [(9, 5), (12, 8)],
 [(9, 6), (11, 8)],
 [(9, 7), (10, 8)],
 [(10, 0), (12, 2)],
 [(10, 1), (12, 3)],
 [(10, 2), (11, 3)],
 [(10, 3), (11, 4)],
 [(10, 4), (11, 5)],
 [(10, 5), (12, 7)],
 [(10, 6), (12, 8)],
 [(10, 7), (12, 9)],
 [(10, 8), (11, 9)],
 [(11, 0), (12, 1)],
 [(11, 1), (12, 2)],
 [(11, 2), (12, 3)],
 [(11, 5), (12, 6)],
 [(11, 6), (12, 7)],
 [

<h3>find_squares_boolean, I created this function, but I didn't work with it , so don't consider it</h3>

In [143]:
def find_squares_boolean(matrix):
    squares = []
    sizes = []
    found_squares = False
    for i in range(len(matrix)):
        for j in range(i+1):
            if matrix[i][j] == 1:
                square_size = 1
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                if square_size > 1:
                    squares.append([(i, j), (i + square_size - 1, j + square_size - 1)])
                    sizes.append(square_size)
                    found_squares = True
    if found_squares:
        return squares, sizes
    else:
        return False
result

[[(2, 0), (3, 1)],
 [(3, 0), (5, 2)],
 [(3, 1), (4, 2)],
 [(4, 0), (7, 3)],
 [(4, 1), (6, 3)],
 [(4, 2), (5, 3)],
 [(5, 0), (9, 4)],
 [(5, 1), (8, 4)],
 [(5, 2), (7, 4)],
 [(5, 3), (6, 4)],
 [(6, 0), (11, 5)],
 [(6, 1), (10, 5)],
 [(6, 2), (9, 5)],
 [(6, 3), (8, 5)],
 [(6, 4), (7, 5)],
 [(7, 0), (11, 4)],
 [(7, 1), (11, 5)],
 [(7, 2), (11, 6)],
 [(7, 3), (10, 6)],
 [(7, 4), (9, 6)],
 [(7, 5), (8, 6)],
 [(8, 0), (11, 3)],
 [(8, 1), (11, 4)],
 [(8, 2), (11, 5)],
 [(8, 3), (11, 6)],
 [(8, 4), (11, 7)],
 [(8, 5), (10, 7)],
 [(8, 6), (9, 7)],
 [(9, 0), (12, 3)],
 [(9, 1), (11, 3)],
 [(9, 2), (11, 4)],
 [(9, 3), (11, 5)],
 [(9, 4), (11, 6)],
 [(9, 5), (12, 8)],
 [(9, 6), (11, 8)],
 [(9, 7), (10, 8)],
 [(10, 0), (12, 2)],
 [(10, 1), (12, 3)],
 [(10, 2), (11, 3)],
 [(10, 3), (11, 4)],
 [(10, 4), (11, 5)],
 [(10, 5), (12, 7)],
 [(10, 6), (12, 8)],
 [(10, 7), (12, 9)],
 [(10, 8), (11, 9)],
 [(11, 0), (12, 1)],
 [(11, 1), (12, 2)],
 [(11, 2), (12, 3)],
 [(11, 5), (12, 6)],
 [(11, 6), (12, 7)],
 [

In [144]:
sizes

[2,
 3,
 2,
 4,
 3,
 2,
 5,
 4,
 3,
 2,
 6,
 5,
 4,
 3,
 2,
 5,
 5,
 5,
 4,
 3,
 2,
 4,
 4,
 4,
 4,
 4,
 3,
 2,
 4,
 3,
 3,
 3,
 3,
 4,
 3,
 2,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 4,
 3,
 2,
 5,
 4,
 3,
 2,
 5,
 4,
 4,
 3,
 2,
 5,
 4,
 3,
 3,
 3,
 2,
 5,
 4,
 3,
 2,
 2,
 2,
 2,
 5,
 4,
 3,
 2,
 3,
 2,
 4,
 4,
 3,
 2,
 4,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 3,
 2,
 2,
 5,
 5,
 4,
 3,
 2,
 4,
 4,
 4,
 4,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 4,
 3,
 2,
 5,
 4,
 3,
 2,
 6,
 5,
 4,
 3,
 2,
 7,
 6,
 5,
 4,
 3,
 2,
 8,
 7,
 6,
 5,
 4,
 3,
 2,
 7,
 7,
 7,
 6,
 5,
 4,
 3,
 2,
 6,
 6,
 6,
 6,
 6,
 5,
 4,
 3,
 2,
 2,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 3,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 2,
 2,
 3,


<h3>Find squares function / another version I didn't work with. Don't consider it. </h3>

In [145]:
def find_squares2(matrix):
    squares = []
    for i in range(len(matrix)):
        for j in range(i+1):
            if matrix[i][j] == 1:
                square_size = 1
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                if square_size > 1:
                    squares.append([(i, j), (i + square_size - 1, j + square_size - 1), square_size])
    return squares
result2 = find_squares2(b)
result2 # this function returns the squares and their size in the same list

[[(2, 0), (3, 1), 2],
 [(3, 0), (5, 2), 3],
 [(3, 1), (4, 2), 2],
 [(4, 0), (7, 3), 4],
 [(4, 1), (6, 3), 3],
 [(4, 2), (5, 3), 2],
 [(5, 0), (9, 4), 5],
 [(5, 1), (8, 4), 4],
 [(5, 2), (7, 4), 3],
 [(5, 3), (6, 4), 2],
 [(6, 0), (11, 5), 6],
 [(6, 1), (10, 5), 5],
 [(6, 2), (9, 5), 4],
 [(6, 3), (8, 5), 3],
 [(6, 4), (7, 5), 2],
 [(7, 0), (11, 4), 5],
 [(7, 1), (11, 5), 5],
 [(7, 2), (11, 6), 5],
 [(7, 3), (10, 6), 4],
 [(7, 4), (9, 6), 3],
 [(7, 5), (8, 6), 2],
 [(8, 0), (11, 3), 4],
 [(8, 1), (11, 4), 4],
 [(8, 2), (11, 5), 4],
 [(8, 3), (11, 6), 4],
 [(8, 4), (11, 7), 4],
 [(8, 5), (10, 7), 3],
 [(8, 6), (9, 7), 2],
 [(9, 0), (12, 3), 4],
 [(9, 1), (11, 3), 3],
 [(9, 2), (11, 4), 3],
 [(9, 3), (11, 5), 3],
 [(9, 4), (11, 6), 3],
 [(9, 5), (12, 8), 4],
 [(9, 6), (11, 8), 3],
 [(9, 7), (10, 8), 2],
 [(10, 0), (12, 2), 3],
 [(10, 1), (12, 3), 3],
 [(10, 2), (11, 3), 2],
 [(10, 3), (11, 4), 2],
 [(10, 4), (11, 5), 2],
 [(10, 5), (12, 7), 3],
 [(10, 6), (12, 8), 3],
 [(10, 7), (12, 9), 

<h3>Extract first element (x axis) Function </h3>
<h6>This function  gets the first elements of the tuples in each list in result variable.<br>
    e.g: (2, 0), (3, 1) ; here this function would return (2,3)

In [146]:
def extract_first_elements_x(lst):
    index = []
    for inner_list in lst:
        inner_result = []
        for tup in inner_list:
            inner_result.append(tup[0])
        index.append(tuple(inner_result))
    return index
x_result = extract_first_elements_x(result)
x_result

[(2, 3),
 (3, 5),
 (3, 4),
 (4, 7),
 (4, 6),
 (4, 5),
 (5, 9),
 (5, 8),
 (5, 7),
 (5, 6),
 (6, 11),
 (6, 10),
 (6, 9),
 (6, 8),
 (6, 7),
 (7, 11),
 (7, 11),
 (7, 11),
 (7, 10),
 (7, 9),
 (7, 8),
 (8, 11),
 (8, 11),
 (8, 11),
 (8, 11),
 (8, 11),
 (8, 10),
 (8, 9),
 (9, 12),
 (9, 11),
 (9, 11),
 (9, 11),
 (9, 11),
 (9, 12),
 (9, 11),
 (9, 10),
 (10, 12),
 (10, 12),
 (10, 11),
 (10, 11),
 (10, 11),
 (10, 12),
 (10, 12),
 (10, 12),
 (10, 11),
 (11, 12),
 (11, 12),
 (11, 12),
 (11, 12),
 (11, 12),
 (11, 12),
 (11, 12),
 (11, 12),
 (15, 16),
 (16, 18),
 (16, 17),
 (17, 20),
 (17, 19),
 (17, 18),
 (18, 22),
 (18, 21),
 (18, 20),
 (18, 19),
 (19, 23),
 (19, 22),
 (19, 22),
 (19, 21),
 (19, 20),
 (20, 24),
 (20, 23),
 (20, 22),
 (20, 22),
 (20, 22),
 (20, 21),
 (21, 25),
 (21, 24),
 (21, 23),
 (21, 22),
 (21, 22),
 (21, 22),
 (21, 22),
 (22, 26),
 (22, 25),
 (22, 24),
 (22, 23),
 (22, 24),
 (22, 23),
 (23, 26),
 (23, 26),
 (23, 25),
 (23, 24),
 (23, 26),
 (23, 25),
 (23, 24),
 (24, 26),
 (24, 2

<h3>Extract first element (Y axis) Function </h3>
<h6>This function  gets the second elements of the tuples in each list in result variable.<br>
    e.g: (2, 0), (3, 1) ; here this function would return (0,1)

In [147]:
def extract_first_elements_y(lst):
    index = []
    for inner_list in lst:
        inner_result = []
        for tup in inner_list:
            inner_result.append(tup[1])
        index.append(tuple(inner_result))
    return index
y_result = extract_first_elements_y(result)
y_result

[(0, 1),
 (0, 2),
 (1, 2),
 (0, 3),
 (1, 3),
 (2, 3),
 (0, 4),
 (1, 4),
 (2, 4),
 (3, 4),
 (0, 5),
 (1, 5),
 (2, 5),
 (3, 5),
 (4, 5),
 (0, 4),
 (1, 5),
 (2, 6),
 (3, 6),
 (4, 6),
 (5, 6),
 (0, 3),
 (1, 4),
 (2, 5),
 (3, 6),
 (4, 7),
 (5, 7),
 (6, 7),
 (0, 3),
 (1, 3),
 (2, 4),
 (3, 5),
 (4, 6),
 (5, 8),
 (6, 8),
 (7, 8),
 (0, 2),
 (1, 3),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 7),
 (6, 8),
 (7, 9),
 (8, 9),
 (0, 1),
 (1, 2),
 (2, 3),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10),
 (13, 14),
 (13, 15),
 (14, 15),
 (13, 16),
 (14, 16),
 (15, 16),
 (13, 17),
 (14, 17),
 (15, 17),
 (16, 17),
 (13, 17),
 (14, 17),
 (15, 18),
 (16, 18),
 (17, 18),
 (13, 17),
 (14, 17),
 (15, 17),
 (16, 18),
 (17, 19),
 (18, 19),
 (13, 17),
 (14, 17),
 (15, 17),
 (16, 17),
 (17, 18),
 (18, 19),
 (19, 20),
 (13, 17),
 (14, 17),
 (15, 17),
 (16, 17),
 (19, 21),
 (20, 21),
 (13, 16),
 (14, 17),
 (15, 17),
 (16, 17),
 (19, 22),
 (20, 22),
 (21, 22),
 (13, 15),
 (14, 16),
 (15, 17),
 (16, 18),
 (17, 19),
 (18, 20),
 (19,

<h3>A little summary</h3>

In [148]:
print(sizes)
print(x_result)
print(y_result)

[2, 3, 2, 4, 3, 2, 5, 4, 3, 2, 6, 5, 4, 3, 2, 5, 5, 5, 4, 3, 2, 4, 4, 4, 4, 4, 3, 2, 4, 3, 3, 3, 3, 4, 3, 2, 3, 3, 2, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 4, 3, 2, 5, 4, 3, 2, 5, 4, 4, 3, 2, 5, 4, 3, 3, 3, 2, 5, 4, 3, 2, 2, 2, 2, 5, 4, 3, 2, 3, 2, 4, 4, 3, 2, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 4, 3, 2, 2, 5, 5, 4, 3, 2, 4, 4, 4, 4, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 4, 3, 2, 5, 4, 3, 2, 6, 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 8, 7, 6, 5, 4, 3, 2, 7, 7, 7, 6, 5, 4, 3, 2, 6, 6, 6, 6, 6, 5, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5, 4, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 2, 3, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 7, 6, 5, 4, 4, 3, 2, 2, 2, 2, 2, 2, 3, 7, 6, 5, 4, 3, 3, 2, 5, 4, 3, 2, 2, 6, 6, 5, 4, 3, 

<h3>This function returns the index of the index of the square that has the biggest size

In [149]:

def index_of_biggest_value(lst):
    max_val = max(lst)
    max_index = lst.index(max_val)

    if lst.count(max_val) == 1:
        return max_index

    closest_index = None
    min_distance = len(lst)

    for i, val in enumerate(lst):
        if val == max_val:
            distance = abs(i - max_index)
            if distance < min_distance:
                closest_index = i
                min_distance = distance
    return closest_index
l = [2,2,2,2,3,2]
biggest = index_of_biggest_value(sizes)
biggest

466

<h3> This function takes as argument the index and the lists of the coordinates of the squares.<br>
    The output is the tuples that have the index i in the argument

In [150]:
def get_element_combination(index,result_x,result_y):
    u = result_x[index]
    v = result_y[index]
    return u,v

element_combination = get_element_combination(biggest,x_result,y_result)
element_combination

((77, 85), (66, 74))

<h3>This function takes 2 tuples as argument and makes an enumeration starting from the smallest element of both tuples to the biggest

In [151]:
def get_numbers_between_tuples(tuples):
    start = min([min(t) for t in tuples])
    end = max([max(t) for t in tuples])
    return [num for num in range(start, end+1)]
numbers = get_numbers_between_tuples(element_combination)
numbers

[66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85]

<h3>Get Combinations function</h3>
<h3>This function does the clustering by creating a cliques from the list of numbers it gets as argument

In [152]:
from itertools import combinations

def get_combinations(lst):
    # Generate all 2-dimensional combinations of the numbers in the list
    combos = combinations(lst, 2)
    
    # Filter out any tuples that have a length other than 2
    valid_combos = [combo for combo in combos if len(combo) == 2]
    
    return valid_combos

combo = get_combinations(numbers)
print(combo)

[(66, 67), (66, 68), (66, 69), (66, 70), (66, 71), (66, 72), (66, 73), (66, 74), (66, 75), (66, 76), (66, 77), (66, 78), (66, 79), (66, 80), (66, 81), (66, 82), (66, 83), (66, 84), (66, 85), (67, 68), (67, 69), (67, 70), (67, 71), (67, 72), (67, 73), (67, 74), (67, 75), (67, 76), (67, 77), (67, 78), (67, 79), (67, 80), (67, 81), (67, 82), (67, 83), (67, 84), (67, 85), (68, 69), (68, 70), (68, 71), (68, 72), (68, 73), (68, 74), (68, 75), (68, 76), (68, 77), (68, 78), (68, 79), (68, 80), (68, 81), (68, 82), (68, 83), (68, 84), (68, 85), (69, 70), (69, 71), (69, 72), (69, 73), (69, 74), (69, 75), (69, 76), (69, 77), (69, 78), (69, 79), (69, 80), (69, 81), (69, 82), (69, 83), (69, 84), (69, 85), (70, 71), (70, 72), (70, 73), (70, 74), (70, 75), (70, 76), (70, 77), (70, 78), (70, 79), (70, 80), (70, 81), (70, 82), (70, 83), (70, 84), (70, 85), (71, 72), (71, 73), (71, 74), (71, 75), (71, 76), (71, 77), (71, 78), (71, 79), (71, 80), (71, 81), (71, 82), (71, 83), (71, 84), (71, 85), (72, 73),

<h3>This function writes the clique we got from the combination in the file destination</h3>

In [153]:
def write_tuples_to_file(tuples_list, filename):
    with open(filename, "a") as file:
        for tpl in tuples_list:
            incremented_tpl = (tpl[0] + 1, tpl[1] + 1)
            file.write(str(incremented_tpl[0]) + " " + str(incremented_tpl[1]) + "\n")
write_tuples_to_file(combo,"cluster1")

<h3>After we got our clique graph, we should no longer consider the vertices from that clique in a new iteration.<br>
<h3>So this matrix sets to 0 all the rows of the vertices from the clique 

In [154]:
def set_triangular_rows_to_zero(matrix, row_indexes):
    for i in row_indexes:
        matrix[i, :i] = 0
        #matrix[:, i] = 0
    return matrix
#d = np.tril(a)
b # You can see the difference that happened to b after executing the function
set_triangular_rows_to_zero(b, numbers)


array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 1, 0]])

In [155]:
def set_triangular_col_to_zero(matrix, row_indexes):
    for i in row_indexes:
        #matrix[i, :i] = 0
        matrix[:, i] = 0
    return matrix
set_triangular_col_to_zero(b, numbers)

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 1, 0]])

<H2> The final function that summaries all the other functions</h2><br>

In [156]:
def make_cluster(matrix,filename):
    result, sizes = find_squares(matrix)
    x_result = extract_first_elements_x(result)
    y_result = extract_first_elements_y(result)
    biggest = index_of_biggest_value(sizes)
    elements_of_combination = get_element_combination(biggest,x_result,y_result)
    numbers = get_numbers_between_tuples(elements_of_combination)
    combo = get_combinations(numbers)
    write_tuples_to_file(combo,filename)
    matrix = set_triangular_rows_to_zero(matrix, numbers)
    matrix = set_triangular_col_to_zero(matrix, numbers)
    result,sizes = find_squares(matrix)
    if result:
        return make_cluster(matrix, filename)
    else : 
        print("Done")
        
#b = np.tril(a)
#b
make_cluster(b,"cluster2")




Done
