Ouvrir le fichier et représenter le graphe

<h3>Represent Data in adjancency matrix </h3>

In [1]:
import numpy as np
import itertools

graph = open("C:/Users/nizar/Desktop/wiss/heur/heur001.gr", 'r')
p,cep,n_vertices, n_edges=graph.readline().split()    #get first line of data in variables
adjacency_matrix = [[0] * int(n_vertices) for _ in range(int(n_vertices))]  #Declare a n_edges dimension matrix full of zeros 
for line in graph:     #Traverse the matrix
    u, v = map(int, line.split())    #Split the line into two variables since we have 2 integers
    adjacency_matrix[u-1][v-1] = 1   #Replacing zeros with 1 if there is a link between 2 vertices
    adjacency_matrix[v-1][u-1] = 1
#print(adjacency_matrix)
a=np.matrix(adjacency_matrix)        #We want a numpy matrix huh ;)
print(a) 


[[0 1 1 1 1 1 1 1 1 0]
 [1 0 1 1 1 1 0 0 1 0]
 [1 1 0 1 1 1 0 0 1 1]
 [1 1 1 0 1 1 1 0 0 1]
 [1 1 1 1 0 1 0 0 0 1]
 [1 1 1 1 1 0 0 0 0 1]
 [1 0 0 1 0 0 0 1 1 1]
 [1 0 0 0 0 0 1 0 1 1]
 [1 1 1 0 0 0 1 1 0 1]
 [0 0 1 1 1 1 1 1 1 0]]


For visualisation purposes, i did this

In [2]:
b=np.tril(a)  #For esthetical reasons, I only keep the lower part of the matrix, no data is lost though
#for i in range(len(b)):
    #for j in range(i):
       # print(b[i][j])
print(b)
for i in range(1,len(b),1):  # loop over rows
    for j in range(i+1):  # loop over columns
        if b[i][j] == 1:
            print("1", end=" ")
        #print(i, end=" ")   print a star and a space
    print() 

[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0]
 [1 1 1 0 0 0 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 0]]
1 
1 1 
1 1 1 
1 1 1 1 
1 1 1 1 1 
1 1 
1 1 
1 1 1 1 1 
1 1 1 1 1 1 1 


Here is a code that works pretty well

<h4>Find squares function, but I didn't work with it actually </h4>

In [3]:
def find_squares_ones(matrix):
    squares = []                    # initialize an empty list to store the squares of ones
    for i in range(len(matrix)):    # loop through the rows of the matrix
        for j in range(i+1):  # loop through the columns, but only the triangular half bottom of the adjacency matrix.
            if matrix[i][j] == 1:        # if the current element is 1, start looking for a square
                square_size = 1  # start with a square of size 1
                # keep increasing the size of the square as long as all the elements within the square are 1's
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                # if we find a square of size greater than 1, add it to the list of squares
                if square_size > 1:
                    squares.append([[1]*square_size]*square_size)
    return squares  # return the list of squares of ones
find_squares_ones(b)

[[[1, 1], [1, 1]],
 [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]]]

Perfect, now i have my squares. <br>
Basically, this function takes a matrix as an argument and seeks for every possible square of 1s.<br>
E.G :<br>
1 1 1<br>
1 1 1<br>
1 1 1<br>
or :<br>
1 1 <br>
1 1<br>
or whatever <br>
The return statement is a list. Each element is also a list that contains the coordinates of the top leftmost element and the bottom rightmost element.

<h3>Find squares function</h3>

In [4]:
def find_squares(matrix):
    squares = []
    sizes = []
    for i in range(len(matrix)):   # initialize an empty list to store the squares of ones
        for j in range(i+1):       # loop through the rows of the matrix
            if matrix[i][j] == 1:  # loop through the columns, but only the triangular half bottom of the adjacency matrix.
                square_size = 1    # if the current element is 1, start looking for a square
                # start with a square of size 1
                # keep increasing the size of the square as long as all the elements within the square are 1's
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                    # i + square_size < len(matrix) : ensures that our square bottom row is inside our matrix
                    # j + square_size < len(matrix[i]) : ensures that the right column of the square is inside it too
                    # all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)) : ensures that all element of the square is 1
                # if we find a square of size greater than 1, add it to the list of squares and sizes
                if square_size > 1:
                    squares.append([(i, j), (i + square_size - 1, j + square_size - 1)]) # Get the sizes in a list
                    sizes.append(square_size)
    return squares, sizes
result, sizes = find_squares(b)
result

[[(2, 0), (3, 1)],
 [(3, 0), (5, 2)],
 [(3, 1), (4, 2)],
 [(4, 0), (5, 1)],
 [(4, 1), (5, 2)],
 [(4, 2), (5, 3)],
 [(8, 6), (9, 7)]]

In [5]:
def find_squares_boolean(matrix):
    squares = []
    sizes = []
    found_squares = False
    for i in range(len(matrix)):
        for j in range(i+1):
            if matrix[i][j] == 1:
                square_size = 1
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                if square_size > 1:
                    squares.append([(i, j), (i + square_size - 1, j + square_size - 1)])
                    sizes.append(square_size)
                    found_squares = True
    if found_squares:
        return squares, sizes
    else:
        return False
h = [[0, 1, 1, 1],
     [1, 1, 1, 1],
     [1, 1, 0, 1],
     [1, 1, 1, 0]]

result3 = find_squares_boolean(b)
if result3:
    squares3, sizes3 = result3
    print(squares3)
    print(sizes3)
else:
    print("No squares found in the matrix")

[[(2, 0), (3, 1)], [(3, 0), (5, 2)], [(3, 1), (4, 2)], [(4, 0), (5, 1)], [(4, 1), (5, 2)], [(4, 2), (5, 3)], [(8, 6), (9, 7)]]
[2, 3, 2, 2, 2, 2, 2]


In [52]:
sizes

[2, 3, 2, 2, 2, 2, 2]

<h3>Find squares function / another version </h3>

In [53]:
def find_squares2(matrix):
    squares = []
    for i in range(len(matrix)):
        for j in range(i+1):
            if matrix[i][j] == 1:
                square_size = 1
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                if square_size > 1:
                    squares.append([(i, j), (i + square_size - 1, j + square_size - 1), square_size])
    return squares
result2 = find_squares2(b)
result2 # this function returns the squares and their size in the same list

[[(2, 0), (3, 1), 2],
 [(3, 0), (5, 2), 3],
 [(3, 1), (4, 2), 2],
 [(4, 0), (5, 1), 2],
 [(4, 1), (5, 2), 2],
 [(4, 2), (5, 3), 2],
 [(8, 6), (9, 7), 2]]

<h3>Extract first element (x axis) Function </h3>

In [6]:
def extract_first_elements_x(lst):
    index = []
    for inner_list in lst:
        inner_result = []
        for tup in inner_list:
            inner_result.append(tup[0])
        index.append(tuple(inner_result))
    return index
x_result = extract_first_elements_x(result)
x_result

[(2, 3), (3, 5), (3, 4), (4, 5), (4, 5), (4, 5), (8, 9)]

<h3>Extract first element (Y axis) Function </h3>

In [7]:
def extract_first_elements_y(lst):
    index = []
    for inner_list in lst:
        inner_result = []
        for tup in inner_list:
            inner_result.append(tup[1])
        index.append(tuple(inner_result))
    return index
y_result = extract_first_elements_y(result)
y_result

[(0, 1), (0, 2), (1, 2), (0, 1), (1, 2), (2, 3), (6, 7)]

In [8]:
print(sizes)
print(x_result)
print(y_result)

[2, 3, 2, 2, 2, 2, 2]
[(2, 3), (3, 5), (3, 4), (4, 5), (4, 5), (4, 5), (8, 9)]
[(0, 1), (0, 2), (1, 2), (0, 1), (1, 2), (2, 3), (6, 7)]


In [9]:
#def max_index(lst):
 #   biggest = lst.index(max(sizes))
  #  return biggest
#biggest = max_index(sizes)
#biggest
def index_of_biggest_value(lst):
    max_val = max(lst)
    max_index = lst.index(max_val)

    if lst.count(max_val) == 1:
        return max_index

    closest_index = None
    min_distance = len(lst)

    for i, val in enumerate(lst):
        if val == max_val:
            distance = abs(i - max_index)
            if distance < min_distance:
                closest_index = i
                min_distance = distance

    return closest_index
l = [2,2,2,2,3,2]
biggest = index_of_biggest_value(sizes)
biggest

1

In [10]:
def get_element_combination(index):
    u = x_result[index]
    v = y_result[index]
    return u,v
element_combination = get_element_combination(biggest)
element_combination

((3, 5), (0, 2))

In [11]:
def get_numbers_between_tuples(tuples):
    start = min([min(t) for t in tuples])
    end = max([max(t) for t in tuples])
    return [num for num in range(start, end+1)]
numbers = get_numbers_between_tuples(element_combination)
numbers

[0, 1, 2, 3, 4, 5]

<h3>Get Combinations function</h3>

In [12]:
from itertools import combinations

def get_combinations(lst):
    # Generate all 2-dimensional combinations of the numbers in the list
    combos = combinations(lst, 2)
    
    # Filter out any tuples that have a length other than 2
    valid_combos = [combo for combo in combos if len(combo) == 2]
    
    return valid_combos

combo = get_combinations(numbers)
print(combo)

[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5)]


In [13]:
def write_tuples_to_file(tuples_list, filename):
    with open(filename, "a") as file:
        for tpl in tuples_list:
            incremented_tpl = (tpl[0] + 1, tpl[1] + 1)
            file.write(str(incremented_tpl[0]) + " " + str(incremented_tpl[1]) + "\n")
write_tuples_to_file(combo,"cluster")

In [14]:
def set_triangular_rows_to_zero(matrix, row_indexes):
    for i in row_indexes:
        matrix[i, :i] = 0
    return matrix
numbers
#d = np.tril(a)
e = b
e = set_triangular_rows_to_zero(e,numbers)
e

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0]])

In [34]:
def make_clusters(matrix, filename):
    result, sizes = find_squares(matrix)
    if result : 
        x_result = extract_first_elements_x(result)
        y_result = extract_first_elements_y(result)
        biggest = index_of_biggest_value(sizes)
        elements_of_combination = get_element_combination(biggest)
        numbers = get_numbers_between_tuples(elements_of_combination)
        combo = get_combinations(numbers)
        write_tuples_to_file(combo,filename)
        matrix = set_triangular_rows_to_zero(matrix, numbers)
        del result,sizes
        return make_clusters(matrix,filename)
    else : 
        print("Done")
#b = np.tril(a)
make_clusters(b,"cluster")

#make_clusters(b,"cluster2")
#result, sizes = find_squares(b)
#if result : 
 #   x_result = extract_first_elements_x(result)
 #   y_result = extract_first_elements_y(result)
 #   biggest = index_of_biggest_value(sizes)
 #   elements_of_combination = get_element_combination(biggest)
 #   numbers = get_numbers_between_tuples(elements_of_combination)
 #   combo = get_combinations(numbers)
 #   write_tuples_to_file(combo,"cluster")
 #   b = set_triangular_rows_to_zero(b, numbers)
#else:
#    print("Done")


IndexError: list index out of range