Ouvrir le fichier et représenter le graphe

In [21]:
graph = open("C:/Users/nizar/Desktop/wiss/heur/heur003.gr", 'r')
p,cep,e,f=graph.readline().split()
#next(graph)
lines = graph.readlines()
#for line in lines:
#    print(line)

In [92]:
import numpy as np
graph = open("C:/Users/nizar/Desktop/wiss/heur/heur001.gr", 'r')
p,cep,n_vertices, n_edges=graph.readline().split()    #get first line of data in variables
adjacency_matrix = [[0] * int(n_vertices) for _ in range(int(n_vertices))]  #Declare a n_edges dimension matrix full of zeros 
for line in graph:     #Traverse the matrix
    u, v = map(int, line.split())    #Split the line into two variables since we have 2 integers
    adjacency_matrix[u-1][v-1] = 1   #Replacing zeros with 1 if there is a link between 2 edges
    adjacency_matrix[v-1][u-1] = 1
#print(adjacency_matrix)
a=np.matrix(adjacency_matrix)        #We want a numpy matrix huh ;)
print(a) 


[[0 1 1 1 1 1 1 1 1 0]
 [1 0 1 1 1 1 0 0 1 0]
 [1 1 0 1 1 1 0 0 1 1]
 [1 1 1 0 1 1 1 0 0 1]
 [1 1 1 1 0 1 0 0 0 1]
 [1 1 1 1 1 0 0 0 0 1]
 [1 0 0 1 0 0 0 1 1 1]
 [1 0 0 0 0 0 1 0 1 1]
 [1 1 1 0 0 0 1 1 0 1]
 [0 0 1 1 1 1 1 1 1 0]]


I tried to view only the y, but i quickly forget what I had in mind, i prefered the first approach

In [93]:
b=np.tril(a)  #For esthetical reasons, I only keep the lower part of the matrix, no data is lost though
rows, cols = np.tril_indices(len(a))

#for i in range(len(b)):
    #for j in range(i):
       # print(b[i][j])
for i in range(1,len(b),1):  # loop over rows
    for j in range(i+1):  # loop over columns
        if b[i][j] == 1:
            print("y", end=" ")
        #print(i, end=" ")   print a star and a space
    print() 
print(b)

y 
y y 
y y y 
y y y y 
y y y y y 
y y 
y y 
y y y y y 
y y y y y y y 
[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0]
 [1 1 1 0 0 0 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 0]]


Here is a code that works pretty well

In [94]:
def find_squares(matrix):
    squares = []                    # initialize an empty list to store the squares of ones
    for i in range(len(matrix)):    # loop through the rows of the matrix
        for j in range(i+1):  # loop through the columns, but only the triangular half bottom of the adjacency matrix.
            if matrix[i][j] == 1:        # if the current element is 1, start looking for a square
                square_size = 1  # start with a square of size 1
                # keep increasing the size of the square as long as all the elements within the square are 1's
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                # if we find a square of size greater than 1, add it to the list of squares
                if square_size > 1:
                    squares.append([[1]*square_size]*square_size)
    return squares  # return the list of squares of ones
find_squares(b)

[[[1, 1], [1, 1]],
 [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]],
 [[1, 1], [1, 1]]]

Perfect, now i have my squares.
Basically, this function takes a matrix as an argument and seeks for every possible square of 1s.
E.g: 1 1 1    or   1 1    or whatever
     1 1 1         1 1
     1 1 1
The return statement is a list. Each element is also a list that contains the coordinates of the top leftmost element and the bottom rightmost element.

In [95]:
def find_squares2(matrix):
    squares = []
    for i in range(len(matrix)):   # initialize an empty list to store the squares of ones
        for j in range(i+1):       # loop through the rows of the matrix
            if matrix[i][j] == 1:  # loop through the columns, but only the triangular half bottom of the adjacency matrix.
                square_size = 1    # if the current element is 1, start looking for a square
                # start with a square of size 1
                # keep increasing the size of the square as long as all the elements within the square are 1's
                while i + square_size < len(matrix) and j + square_size < len(matrix[i]) and all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)):
                    square_size += 1
                    # i + square_size < len(matrix) : ensures that our square bottom row is inside our matrix
                    # j + square_size < len(matrix[i]) : ensures that the right column of the square is inside it too
                    # all(matrix[x][y] == 1 for x in range(i, i + square_size + 1) for y in range(j, j + square_size + 1)) : ensures that all element of the square is 1
                # if we find a square of size greater than 1, add it to the list of squares
                if square_size > 1:
                    squares.append([(i, j), (i + square_size - 1, j + square_size - 1)])
    return squares
find_squares2(b)

[[(2, 0), (3, 1)],
 [(3, 0), (5, 2)],
 [(3, 1), (4, 2)],
 [(4, 0), (5, 1)],
 [(4, 1), (5, 2)],
 [(4, 2), (5, 3)],
 [(8, 6), (9, 7)]]